### ISSUE TITLE
how do i install/use this?

### ISSUE THREAD

**Issue by classicalokaku** [SturmB/totk-armor-upgrade-tracker#1]
im a bit confused on how to actually use this program.

**Comment by SturmB** [comment]
I apologize for the ambiguity. Unlike most GitHub projects, this isn't really meant to be downloaded, compiled, and run locally on your own computer. Although, if you are familiar with how to run [Laravel](https://laravel.com) projects locally, you certainly could do so.

Instead, this will be a web app as soon as I finish with it, almost identical to the [Breath of the Wild Armor Tracker](https://botw.armortracker.com). I've updated the README to hopefully be more clear about that.

As of right now, however, it is still being worked on and not ready to be published. As soon as it's ready, I'll put a link in the README.

**Comment by classicalokaku** [comment]
do you have any idea of when this might become available for use?

**Comment by SturmB** [comment]
Sorry for the delay in responding; I've been busy the last few days putting in the final touches.

Indeed, it is now available! 🎉

Check it out at https://totk.armortracker.com/.

Feel free to come back and open an issue if you happen to have any. I'll still be working on it in the meantime.
